on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Solhint Docker image
        run: |
          repository_name="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/solhint-checker"

          docker build -t $repository_name:${{ github.sha }} -f solhint.dockerfile .
          docker tag $repository_name:${{ github.sha }} $repository_name:latest
  
      - name: Push Solhint Docker image
        run: |
          repository_name="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/solhint-checker"

          docker push $repository_name:${{ github.sha }}
          docker push $repository_name:latest
      - name: Run Solidity Security Check
        uses: docker://ghcr.io/zerbinidamata/hephaestussolidityguard/solhint-checker:latest
