on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Run Solidity Security Check
        uses: docker://ghcr.io/zerbinidamata/hephaestussolidityguard/solhint:latest
