on: [push]

jobs:
  push_test_image:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Solhint Docker image
        run: |
          repository_name="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/solhint-checker"

          docker build -t $repository_name:${{ github.sha }} -f solhint.dockerfile .
          docker tag $repository_name:${{ github.sha }} $repository_name:latest
  
      - name: Run Solhint Docker image
        run: |
          repository_name="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/solhint-checker"

          docker run $repository_name:latest
